{
 "title": "F1 Telemetry",
 "time": { "from": "2022-06-18T10:59:05.090Z", "to": "2022-06-18T11:01:04.587Z" },
 "panels": [
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_speed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_drs\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ERS Remaining Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_ersStoreEnergy\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_ersDeployMode\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Tyres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Compound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_actualTyreCompound\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tyres Age Laps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_tyresAgeLaps\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tyres Inner Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_tyres_inner_temperature_fl\" or r[\"_field\"] == \"m_tyres_inner_temperature_fr\" or r[\"_field\"] == \"m_tyres_inner_temperature_rl\" or r[\"_field\"] == \"m_tyres_inner_temperature_rr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tyres Surface Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_tyres_surface_temperature_fl\" or r[\"_field\"] == \"m_tyres_surface_temperature_fr\" or r[\"_field\"] == \"m_tyres_surface_temperature_rl\" or r[\"_field\"] == \"m_tyres_surface_temperature_rr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tyres Wear",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_damage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_tyresWear_fl\" or r[\"_field\"] == \"m_tyresWear_fr\" or r[\"_field\"] == \"m_tyresWear_rl\" or r[\"_field\"] == \"m_tyresWear_rr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tyres Damage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_damage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_tyresDamage_fl\" or r[\"_field\"] == \"m_tyresDamage_fr\" or r[\"_field\"] == \"m_tyresDamage_rl\" or r[\"_field\"] == \"m_tyresDamage_rr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Brakes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Brakes Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_brakes_temperature_fl\" or r[\"_field\"] == \"m_brakes_temperature_rl\" or r[\"_field\"] == \"m_brakes_temperature_fr\" or r[\"_field\"] == \"m_brakes_temperature_rr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Brakes Damage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"f1_telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"car_damage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"m_brakesDamage_fl\" or r[\"_field\"] == \"m_brakesDamage_fr\" or r[\"_field\"] == \"m_brakesDamage_rl\" or r[\"_field\"] == \"m_brakesDamage_rr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}